import React from 'react'
import Cloud from './cloud'
export default function whatIsTheCloud(){
    return (
        <div class="flex flex-col">
            <Cloud/>
            <p class="p-16 pb-10 pl-44 text-4xl">What is the cloud?</p>
            <iframe width="560" height="315" class="ml-52" src="https://www.youtube.com/embed/M988_fsOSWo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe><br/>
            <div class="flex flex-row">
                <p class="pl-44 text-lg">"The cloud" refers to servers that are accessed over the Internet, and the software and databases that run on those servers. Cloud servers are located in data centers all over the world. By using cloud computing, users and companies do not have to manage physical servers themselves or run software applications on their own machines.<br/><br/>The cloud enables users to access the same files and applications from almost any device, because the computing and storage takes place on servers in a data center, instead of locally on the user device. This is why a user can log in to their Instagram account on a new phone after their old phone breaks and still find their old account in place, with all their photos, videos, and conversation history. It works the same way with cloud email providers like Gmail or Microsoft Office 365, and with cloud storage providers like Dropbox or Google Drive.<br/><br/></p>
                <img class="w-1/2 h-1/2 pr-44" src="https://cf-assets.www.cloudflare.com/slt3lc6tev37/3YT0gya2bkUeuMrnGxhjAZ/4146c20c214cf001c74c0868ddfb9503/what-is-the-cloud.png"/>
            </div>
            <p class="pl-44 pr-44 text-lg">For businesses, switching to cloud computing removes some IT costs and overhead: for instance, they no longer need to update and maintain their own servers, as the cloud vendor they are using will do that. This especially makes an impact for small businesses that may not have been able to afford their own internal infrastructure but can outsource their infrastructure needs affordably via the cloud. The cloud can also make it easier for companies to operate internationally, because employees and customers can access the same files and applications from any location.</p>
            <p class="p-16 pb-10 pl-44 text-4xl">How does cloud computing work?</p>
            <p class="pl-44 pr-44 text-lg">Cloud computing is possible because of a technology called virtualization. Virtualization allows for the creation of a simulated, digital-only "virtual" computer that behaves as if it were a physical computer with its own hardware. The technical term for such a computer is virtual machine. When properly implemented, virtual machines on the same host machine are sandboxed from one another, so they do not interact with each other at all, and the files and applications from one virtual machine are not visible to the other virtual machines even though they are on the same physical machine.<br/><br/>Virtual machines also make more efficient use of the hardware hosting them. By running many virtual machines at once, one server becomes many servers, and a data center becomes a whole host of data centers, able to serve many organizations. Thus, cloud providers can offer the use of their servers to far more customers at once than they would be able to otherwise, and they can do so at a low cost.<br/><br/>Even if individual servers go down, cloud servers in general should be always online and always available. Cloud vendors generally back up their services on multiple machines and across multiple regions.<br/><br/>Users access cloud services either through a browser or through an app, connecting to the cloud over the Internet - that is, through many interconnected networks - regardless of what device they are using.</p>
            <p class="p-16 pb-10 pl-44 text-4xl">What are the main service models of cloud computing?</p>
            <img class="w-3/4 h-5/6 pl-44 pr-44" src="https://www.cloudflare.com/img/learning/serverless/glossary/platform-as-a-service-paas/saas-paas-iaas-diagram.svg"/><br/>
            <div class="pl-44 pr-44">
                <p class="text-2xl">Software-as-a-Service (SaaS):</p><br/>
                <p class="text-lg">Instead of users installing an application on their device, SaaS applications are hosted on cloud servers, and users access them over the Internet. SaaS is like renting a house: the landlord maintains the house, but the tenant mostly gets to use it as if they owned it. Examples of SaaS applications include Salesforce, MailChimp, and Slack.</p><br/>
                <p class="text-2xl">Platform-as-a-Service (PaaS):</p><br/>
                <p class="text-lg">In this model, companies don't pay for hosted applications; instead they pay for the things they need to build their own applications. PaaS vendors offer everything necessary for building an application, including development tools, infrastructure, and operating systems, over the Internet. PaaS can be compared to renting all the tools and equipment necessary for building a house, instead of renting the house itself. PaaS examples include Heroku and Microsoft Azure.</p><br/>
                <p class="text-2xl">Infrastructure-as-a-Service (IaaS):</p><br/>
                <p class="text-lg">In this model, a company rents the servers and storage they need from a cloud provider. They then use that cloud infrastructure to build their applications. IaaS is like a company leasing a plot of land on which they can build whatever they want — but they need to provide their own building equipment and materials. IaaS providers include DigitalOcean, Google Compute Engine, and OpenStack.<br/><br/>Formerly, SaaS, PaaS, and IaaS were the three main models of cloud computing, and essentially all cloud services fit into one of these categories. However, in recent years a fourth model has emerged.</p><br/>
                <p class="text-2xl">Function-as-a-Service (FaaS):</p><br/>
                <p class="text-lg">FaaS, also known as serverless computing, breaks cloud applications down into even smaller components that only run when they are needed. Imagine if it were possible to rent a house one little bit at a time: for instance, the tenant only pays for the dining room at dinner time, the bedroom while they are sleeping, the living room while they are watching TV, and when they are not using those rooms, they don't have to pay rent on them.<br/><br/>FaaS or serverless applications still run on servers, as do all these models of cloud computing. But they are called "serverless" because they do not run on dedicated machines, and because the companies building the applications do not have to manage any servers.</p><br/>

            </div>
         </div>
    )
}
